"""Prompt bundled asset loader.

Generated by Prompt v156 assets.zip pass.
The real runtime HTML/MD/JS/CSS/SVG assets live in assets.zip with manifest.json.
This module intentionally stays small so Python does not parse a giant base64 literal at startup.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
import zipfile
from pathlib import Path
from typing import Any
import datetime
import traceback
import threading  # thread-ok

from File import File as _CanonicalFile


class File(_CanonicalFile):
    """Data-layer alias for the canonical File wrapper.

    The detector contract expects data.py to expose a File class so raw file
    I/O can be centrally audited. Runtime behavior remains inherited from
    File.py.
    """
    pass


_EXCEPTION_CAPTURE_REENTRANT = False

def _capture_exception_log_path() -> Path:
    try:
        root = Path(__file__).resolve().parents[1] if Path(__file__).resolve().parent.name == 'tools' else Path(__file__).resolve().parent
    except Exception:  # swallow-ok: emergency capture path fallback
        root = Path.cwd()
    return root / 'logs' / 'exceptions.log'


def _capture_exception_db_path() -> Path:
    raw = str(os.environ.get('TRIO_SQLITE_PATH', '') or '').strip()
    if raw:
        return Path(raw).expanduser()
    try:
        root = Path(__file__).resolve().parents[1] if Path(__file__).resolve().parent.name == 'tools' else Path(__file__).resolve().parent
    except Exception:  # swallow-ok: emergency capture path fallback
        root = Path.cwd()
    return root / 'workspaces' / 'prompt_debugger.sqlite3'


def captureException(exc: BaseException | None = None, *, source: str = '', context: str = '', handled: bool = True, extra: str = '') -> int:
    """Trace and persist an exception row for the launcher debugger when SQLAlchemy is available."""
    global _EXCEPTION_CAPTURE_REENTRANT
    if _EXCEPTION_CAPTURE_REENTRANT:
        return 0
    _EXCEPTION_CAPTURE_REENTRANT = True
    row_id = 0
    try:
        if exc is None:
            exc = sys.exc_info()[1]
        type_name = type(exc).__name__ if exc is not None else 'UnknownException'
        message = str(exc or '')
        tb = getattr(exc, '__traceback__', None) if exc is not None else sys.exc_info()[2]
        traceback_text = ''.join(traceback.format_exception(type(exc), exc, tb)) if exc is not None else ''.join(traceback.format_stack())
        created = datetime.datetime.now().isoformat(sep=' ', timespec='microseconds')
        source_text = str(source or Path(__file__).name)
        context_text = str(context or '')
        try:
            target = _capture_exception_log_path()
            target.parent.mkdir(parents=True, exist_ok=True)
            with File.tracedOpen(target, 'a', encoding='utf-8', errors='replace') as handle:
                handle.write(f'{created} [CAPTURED-EXCEPTION] source={source_text} context={context_text} handled={int(bool(handled))} type={type_name} message={message}\n')
                if extra:
                    handle.write(f'{created} [CAPTURED-EXCEPTION:EXTRA] {extra}\n')
                handle.write(traceback_text.rstrip() + '\n')
        except Exception:  # swallow-ok: emergency capture must never break the caller
            pass
        try:
            print(f'[CAPTURED-EXCEPTION] source={source_text} context={context_text} type={type_name}: {message}', file=sys.stderr, flush=True)
        except Exception:  # swallow-ok: hidden-console trace fallback
            pass
        try:
            from sqlalchemy import Column, Integer, Text, create_engine
            from sqlalchemy.orm import DeclarativeBase, sessionmaker
            class CaptureBase(DeclarativeBase):
                pass
            class CaptureExceptionRecord(CaptureBase):
                __tablename__ = 'exceptions'
                id = Column(Integer, primary_key=True, autoincrement=True)
                created = Column(Text)
                source = Column(Text)
                context = Column(Text)
                type_name = Column('type_name', Text)
                message = Column(Text)
                traceback_text = Column('traceback_text', Text)
                source_context = Column('source_context', Text)
                thread = Column(Text)
                pid = Column(Integer)
                handled = Column(Integer, default=1)
                processed = Column(Integer, default=0)
            db_path = _capture_exception_db_path()
            db_path.parent.mkdir(parents=True, exist_ok=True)
            engine = create_engine(f'sqlite:///{db_path}', future=True)
            try:
                CaptureBase.metadata.create_all(engine)
                SessionFactory = sessionmaker(bind=engine, future=True)
                with SessionFactory() as session:
                    row = CaptureExceptionRecord(created=created, source=source_text, context=context_text, type_name=type_name, message=message, traceback_text=traceback_text, source_context=extra, thread=str(getattr(threading.current_thread(), 'name', '') or ''), pid=int(os.getpid()), handled=1 if handled else 0, processed=0)
                    session.add(row)
                    session.flush()
                    row_id = int(getattr(row, 'id', 0) or 0)
                    session.commit()
            finally:
                try:
                    engine.dispose()
                except Exception:  # swallow-ok: cleanup fallback
                    pass
        except Exception as db_error:  # swallow-ok: SQLAlchemy may be unavailable in -S detector mode
            try:
                target = _capture_exception_log_path()
                target.parent.mkdir(parents=True, exist_ok=True)
                with File.tracedOpen(target, 'a', encoding='utf-8', errors='replace') as handle:
                    handle.write(f'{datetime.datetime.now().isoformat(sep=" ", timespec="microseconds")} [CAPTURED-EXCEPTION-DB-FAILED] {type(db_error).__name__}: {db_error}\n')
            except Exception:  # swallow-ok: final fallback
                pass
        return row_id
    finally:
        _EXCEPTION_CAPTURE_REENTRANT = False

DATA_VERSION = 'v172_sound_effects'
ASSETS_ZIP_NAME = 'assets.zip'
ASSETS_ZIP_RELATIVE_PATH = Path('assets') / ASSETS_ZIP_NAME
ASSETS_MANIFEST_NAME = 'manifest.json'


def normalize_path(path: str | Path) -> str:
    return str(path).replace('\\', '/').strip().lstrip('./')


class PromptAssetsBundle:
    """Small zip-backed runtime asset bundle with manifest/MD5 repair support."""

    def __init__(self, bundle_path: str | Path | None = None) -> None:
        self.bundle_path = Path(bundle_path).resolve() if bundle_path else self._find_bundle_path()
        self._manifest: dict[str, Any] | None = None

    @staticmethod
    def _candidate_roots() -> list[Path]:
        roots: list[Path] = []
        def add(value: object) -> None:
            if not value:
                return
            try:
                path = Path(str(value)).resolve()
            except Exception:
                captureException(None, source='data.py', context='except@42')
                return
            if path not in roots:
                roots.append(path)
        add(Path(__file__).resolve().parent)
        add(os.environ.get('PROMPT_ASSETS_ROOT', ''))
        add(os.environ.get('PROMPT_BUNDLE_ROOT', ''))
        add(os.environ.get('PROMPT_ROOT', ''))
        add(getattr(sys, '_MEIPASS', ''))
        try:
            add(Path(sys.executable).resolve().parent)
        except Exception:
            captureException(None, source='data.py', context='except@53')
            pass
        try:
            add(Path.cwd())
        except Exception:
            captureException(None, source='data.py', context='except@57')
            pass
        expanded: list[Path] = []
        for root in roots:
            for candidate in (root, root / '_internal', root / 'Prompt', root / 'Prompt' / '_internal'):
                try:
                    resolved = candidate.resolve()
                except Exception:
                    captureException(None, source='data.py', context='except@64')
                    resolved = candidate
                if resolved not in expanded:
                    expanded.append(resolved)
        return expanded

    @classmethod
    def _find_bundle_path(cls) -> Path:
        for root in cls._candidate_roots():
            for candidate in (root / ASSETS_ZIP_RELATIVE_PATH, root / ASSETS_ZIP_NAME):
                if candidate.exists() and candidate.is_file():
                    return candidate
        return Path(__file__).resolve().parent / ASSETS_ZIP_RELATIVE_PATH

    def available(self) -> bool:
        return self.bundle_path.exists() and self.bundle_path.is_file()

    @property
    def manifest(self) -> dict[str, Any]:
        if self._manifest is None:
            if not self.available():
                self._manifest = {'version': DATA_VERSION, 'file_count': 0, 'raw_bytes': 0, 'files': {}}
            else:
                with zipfile.ZipFile(self.bundle_path, 'r') as archive:
                    self._manifest = json.loads(archive.read(ASSETS_MANIFEST_NAME).decode('utf-8'))
        return self._manifest

    @property
    def files(self) -> dict[str, dict[str, Any]]:
        records = self.manifest.get('files', {})
        return records if isinstance(records, dict) else {}

    def has_file(self, path: str | Path) -> bool:
        return normalize_path(path) in self.files

    def list_files(self, prefix: str = '') -> list[str]:
        wanted = normalize_path(prefix)
        if wanted and not wanted.endswith('/'):
            wanted += '/'
        return sorted(name for name in self.files if not wanted or name.startswith(wanted))

    def read_bytes(self, path: str | Path) -> bytes:  # noqa: nonconform reviewed return contract
        name = normalize_path(path)
        if name not in self.files:
            raise FileNotFoundError(name)
        with zipfile.ZipFile(self.bundle_path, 'r') as archive:
            return archive.read(name)

    def read_text(self, path: str | Path, encoding: str = 'utf-8', errors: str = 'replace') -> str:
        return self.read_bytes(path).decode(encoding, errors)

    def tracedReadText(self, path: str | Path, encoding: str = 'utf-8', errors: str = 'replace') -> str:
        return self.read_bytes(path).decode(encoding, errors)

    def file_info(self, path: str | Path) -> dict[str, object]:
        name = normalize_path(path)
        record = dict(self.files[name])
        record['path'] = name
        record['bundle'] = str(self.bundle_path)
        return record

    def target_matches(self, path: str | Path, target: str | Path) -> bool:
        name = normalize_path(path)
        record = self.files.get(name)
        target_path = Path(target)
        if not record or not target_path.exists() or not target_path.is_file():
            return False
        expected_size = int(record.get('size', -1))
        try:
            if expected_size >= 0 and target_path.stat().st_size != expected_size:
                return False
            expected_md5 = str(record.get('md5', '') or '')
            if expected_md5:
                actual_md5 = hashlib.md5(target_path.read_bytes()).hexdigest()
                return actual_md5 == expected_md5
            return True
        except Exception:
            captureException(None, source='data.py', context='except@137')
            return False

    def needs_update(self, path: str | Path, target: str | Path) -> bool:
        return not self.target_matches(path, target)

    def write_file(self, path: str | Path, target: str | Path, *, overwrite: bool = False) -> bool:
        target_path = Path(target)
        if target_path.exists() and not overwrite and self.target_matches(path, target_path):
            return False
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_bytes(self.read_bytes(path))
        try:
            target_path.chmod(target_path.stat().st_mode | 0o600)
        except Exception:
            captureException(None, source='data.py', context='write-file-chmod')
        return True

    def write_all(self, root: str | Path, *, overwrite: bool = False) -> tuple[int, int]:
        root_path = Path(root)
        written = 0
        skipped = 0
        for name in self.list_files():
            if self.write_file(name, root_path / name, overwrite=overwrite):
                written += 1
            else:
                skipped += 1
        return written, skipped


BUNDLE = PromptAssetsBundle()
EMBEDDED_FILES: dict[str, dict[str, object]] = BUNDLE.files
EMBEDDED_FILE_COUNT = len(EMBEDDED_FILES)
EMBEDDED_RAW_BYTES = int(BUNDLE.manifest.get('raw_bytes', 0) or 0)




def _file_digest(path: Path) -> dict[str, object]:
    try:
        if not path.exists() or not path.is_file():
            return {'exists': path.exists(), 'is_file': path.is_file() if path.exists() else False, 'size': 0, 'md5': '', 'sha256': ''}
        payload = path.read_bytes()
        return {'exists': True, 'is_file': True, 'size': len(payload), 'md5': hashlib.md5(payload).hexdigest(), 'sha256': hashlib.sha256(payload).hexdigest()}
    except Exception as exc:
        captureException(None, source='data.py', context='except@177')
        return {'exists': False, 'is_file': False, 'size': 0, 'md5': '', 'sha256': '', 'error': f'{type(exc).__name__}: {exc}'}


def bundle_debug_snapshot() -> dict[str, object]:
    """Return a serializable flight-recorder snapshot for EXE asset debugging."""
    try:
        roots = [str(root) for root in PromptAssetsBundle._candidate_roots()]
    except Exception as exc:
        captureException(None, source='data.py', context='except@185')
        roots = [f'candidate-root-error:{type(exc).__name__}:{exc}']
    bundle = BUNDLE.bundle_path
    snapshot: dict[str, object] = {
        'data_version': DATA_VERSION,
        'assets_zip_name': ASSETS_ZIP_NAME,
        'assets_zip_relative_path': str(ASSETS_ZIP_RELATIVE_PATH),
        'bundle_path': str(bundle),
        'candidate_roots': roots,
        'bundle_digest': _file_digest(bundle),
        'available': BUNDLE.available(),
        'file_count': len(EMBEDDED_FILES),
        'raw_bytes': EMBEDDED_RAW_BYTES,
    }
    try:
        snapshot['manifest_file_count'] = BUNDLE.manifest.get('file_count', 0)
        snapshot['manifest_raw_bytes'] = BUNDLE.manifest.get('raw_bytes', 0)
    except Exception as exc:
        captureException(None, source='data.py', context='except@202')
        snapshot['manifest_error'] = f'{type(exc).__name__}: {exc}'
    return snapshot


def has_file(path: str | Path) -> bool:
    return BUNDLE.has_file(path)


def list_files(prefix: str = '') -> list[str]:
    return BUNDLE.list_files(prefix)


def read_bytes(path: str | Path) -> bytes:
    return BUNDLE.read_bytes(path)


def tracedReadText(path: str | Path, encoding: str = 'utf-8', errors: str = 'replace') -> str:
    return BUNDLE.tracedReadText(path, encoding=encoding, errors=errors)


def read_text(path: str | Path, encoding: str = 'utf-8', errors: str = 'replace') -> str:
    return tracedReadText(path, encoding=encoding, errors=errors)


def file_info(path: str | Path) -> dict[str, object]:
    return BUNDLE.file_info(path)


def target_matches(path: str | Path, target: str | Path) -> bool:
    return BUNDLE.target_matches(path, target)


def needs_update(path: str | Path, target: str | Path) -> bool:
    return BUNDLE.needs_update(path, target)


def write_file(path: str | Path, target: str | Path, *, overwrite: bool = False) -> bool:
    return BUNDLE.write_file(path, target, overwrite=overwrite)


def write_all(root: str | Path, *, overwrite: bool = False) -> tuple[int, int]:
    return BUNDLE.write_all(root, overwrite=overwrite)


def InsertDebuggerException(payload=None):  # noqa: N802
    from DebugLog import DebugLog
    data = dict(payload or {})
    return DebugLog.saveExceptionFallback(None, source=str(data.get('source') or 'data.py'), context=str(data.get('context') or 'InsertDebuggerException'), handled=bool(data.get('handled', True)), extra=str(data.get('message') or ''))
