from typing import Any, Iterator

class _SqlAny:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def in_(self, values: Any) -> Any: ...
    def asc(self) -> Any: ...
    def desc(self) -> Any: ...

class Column(_SqlAny): ...
class Float(_SqlAny): ...
class Integer(_SqlAny): ...
class String(_SqlAny): ...
class Text(_SqlAny): ...

def create_engine(*args: Any, **kwargs: Any) -> Any: ...
def select(*args: Any, **kwargs: Any) -> Any: ...
def text(*args: Any, **kwargs: Any) -> Any: ...
