from typing import Any, Iterator

class _SqlAny:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...

class DeclarativeBase:
    metadata: Any
    __table__: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Session(_SqlAny): ...
class sessionmaker(_SqlAny): ...
