from typing import Any
class Options:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
class Subsetter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def populate(self, *args: Any, **kwargs: Any) -> None: ...
    def subset(self, *args: Any, **kwargs: Any) -> None: ...
def load_font(*args: Any, **kwargs: Any) -> Any: ...
def save_font(*args: Any, **kwargs: Any) -> Any: ...
