from typing import Any
class TTFont:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __enter__(self) -> 'TTFont': ...
    def __exit__(self, *args: Any) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __contains__(self, key: object) -> bool: ...
    def getBestCmap(self, *args: Any, **kwargs: Any) -> dict[int, str]: ...
    def getGlyphOrder(self, *args: Any, **kwargs: Any) -> list[str]: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def close(self) -> None: ...
