from typing import Any, Iterator, ClassVar
class _QtAny:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __bool__(self) -> bool: ...
    def __or__(self, other: Any) -> Any: ...
    def __and__(self, other: Any) -> Any: ...
    def event(self, *args: Any, **kwargs: Any) -> Any: ...
    def mousePressEvent(self, *args: Any, **kwargs: Any) -> Any: ...
    def mouseReleaseEvent(self, *args: Any, **kwargs: Any) -> Any: ...
    def contextMenuEvent(self, *args: Any, **kwargs: Any) -> Any: ...
    def showEvent(self, *args: Any, **kwargs: Any) -> Any: ...
    def moveEvent(self, *args: Any, **kwargs: Any) -> Any: ...
    def resizeEvent(self, *args: Any, **kwargs: Any) -> Any: ...
    def changeEvent(self, *args: Any, **kwargs: Any) -> Any: ...
    def closeEvent(self, *args: Any, **kwargs: Any) -> Any: ...
    def dragEnterEvent(self, *args: Any, **kwargs: Any) -> Any: ...
    def dragMoveEvent(self, *args: Any, **kwargs: Any) -> Any: ...
    def dropEvent(self, *args: Any, **kwargs: Any) -> Any: ...

class Qt(_QtAny):
    UserRole: ClassVar[Any]
    WindowStaysOnTopHint: ClassVar[Any]
    WindowFullScreen: ClassVar[Any]
    WindowMinimized: ClassVar[Any]
    WindowMaximized: ClassVar[Any]
    AlignCenter: ClassVar[Any]
    NonModal: ClassVar[Any]
    Tool: ClassVar[Any]
    QueuedConnection: ClassVar[Any]
    DefaultContextMenu: ClassVar[Any]
    NoButton: ClassVar[Any]
    RightButton: ClassVar[Any]
    CopyAction: ClassVar[Any]
    Horizontal: ClassVar[Any]
    WA_DeleteOnClose: ClassVar[Any]
    ScrollBarAlwaysOff: ClassVar[Any]
    WA_TransparentForMouseEvents: ClassVar[Any]
    CustomContextMenu: ClassVar[Any]
    Vertical: ClassVar[Any]
    AlignRight: ClassVar[Any]
    KeepAspectRatio: ClassVar[Any]
    SmoothTransformation: ClassVar[Any]
    WindowNoState: ClassVar[Any]

class QAbstractItemView(_QtAny):
    SingleSelection: ClassVar[Any]
    ExtendedSelection: ClassVar[Any]
class QAction(_QtAny): ...
class QBrush(_QtAny): ...
class QByteArray(_QtAny):
    @staticmethod
    def fromHex(*args: Any, **kwargs: Any) -> Any: ...
class QCheckBox(_QtAny): ...
class QColor(_QtAny): ...
class QComboBox(_QtAny): ...
class QContextMenuEvent(_QtAny): ...
class QDialog(_QtAny): ...
class QDoubleSpinBox(_QtAny): ...
class QEvent(_QtAny):
    ContextMenu: ClassVar[Any]
    ActivationChange: ClassVar[Any]
    WindowStateChange: ClassVar[Any]
class QEventLoop(_QtAny): ...
class QFont(_QtAny): ...
class QFormLayout(_QtAny): ...
class QGridLayout(_QtAny): ...
class QGroupBox(_QtAny): ...
class QHBoxLayout(_QtAny): ...
class QIcon(_QtAny): ...
class QKeySequence(_QtAny): ...
class QLabel(_QtAny): ...
class QLineEdit(_QtAny):
    Password: ClassVar[Any]
class QListWidget(_QtAny):
    IconMode: ClassVar[Any]
    LeftToRight: ClassVar[Any]
    Adjust: ClassVar[Any]
    Static: ClassVar[Any]
class QListWidgetItem(_QtAny): ...
class QMainWindow(_QtAny): ...
class QMenu(_QtAny): ...
class QMenuBar(_QtAny): ...
class QMetaObject(_QtAny):
    @staticmethod
    def invokeMethod(*args: Any, **kwargs: Any) -> Any: ...
class QMimeData(_QtAny): ...
class QObject(_QtAny): ...
class QPainter(_QtAny): ...
class QPixmap(_QtAny): ...
class QPlainTextEdit(_QtAny):
    NoWrap: ClassVar[Any]
class QPoint(_QtAny): ...
class QPrintDialog(_QtAny): ...
class QPrinter(_QtAny): ...
class QPushButton(_QtAny): ...
class QShortcut(_QtAny): ...
class QSize(_QtAny): ...
class QSplitter(_QtAny): ...
class QStackedWidget(_QtAny): ...
class QStatusBar(_QtAny): ...
class QTabWidget(_QtAny): ...
class QTextBrowser(_QtAny): ...
class QTextCursor(_QtAny):
    End: ClassVar[Any]
    Start: ClassVar[Any]
class QTextDocument(_QtAny):
    FindFlag: ClassVar[Any]
    FindBackward: ClassVar[Any]
class QTextEdit(_QtAny): ...
class QTimer(_QtAny): ...
class QToolBar(_QtAny): ...
class QTreeWidget(_QtAny): ...
class QTreeWidgetItem(_QtAny): ...
class QUrl(_QtAny): ...
class QVBoxLayout(_QtAny): ...
class QWebChannel(_QtAny): ...
class QWebEngineProfile(_QtAny): ...
class QWebEngineScript(_QtAny): ...
class QWebEngineSettings(_QtAny): ...
class QWebEngineView(_QtAny): ...
class QWidget(_QtAny): ...
class Slot(_QtAny): ...

class QApplication(_QtAny):
    @staticmethod
    def instance(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def primaryScreen(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def clipboard(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def activeModalWidget(*args: Any, **kwargs: Any) -> Any: ...

class QFontDatabase(_QtAny):
    FixedFont: ClassVar[Any]
    GeneralFont: ClassVar[Any]
    @staticmethod
    def systemFont(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def removeApplicationFont(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def addApplicationFont(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def applicationFontFamilies(*args: Any, **kwargs: Any) -> Any: ...

class QMessageBox(_QtAny):
    @staticmethod
    def warning(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def critical(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def information(*args: Any, **kwargs: Any) -> Any: ...

class QFileDialog(_QtAny):
    @staticmethod
    def getSaveFileName(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def getOpenFileName(*args: Any, **kwargs: Any) -> Any: ...

class QUrl(_QtAny):
    @staticmethod
    def fromLocalFile(*args: Any, **kwargs: Any) -> Any: ...

class QWebEnginePage(_QtAny):
    JavaScriptConsoleMessageLevel: ClassVar[Any]
    FindFlag: ClassVar[Any]
    FindBackward: ClassVar[Any]
    def javaScriptConsoleMessage(self, *args: Any, **kwargs: Any) -> Any: ...

class QComboBox(_QtAny):
    NoInsert: ClassVar[Any]

class QSizePolicy(_QtAny):
    Expanding: ClassVar[Any]
    Preferred: ClassVar[Any]



# Prompt Pyrite pass: explicit Qt members used by Prompt/start.py.
Qt.WindowNoState: Any
QEvent.ContextMenu: Any
QEvent.ActivationChange: Any
QEvent.WindowStateChange: Any
QMetaObject.invokeMethod: Any
QTextDocument.FindFlag: Any
QTextDocument.FindBackward: Any
QTextCursor.End: Any
QTextCursor.Start: Any
QByteArray.fromHex: Any
QListWidget.IconMode: Any
QListWidget.LeftToRight: Any
QListWidget.Adjust: Any
QListWidget.Static: Any
QAbstractItemView.SingleSelection: Any
QAbstractItemView.ExtendedSelection: Any
QPlainTextEdit.NoWrap: Any
QLineEdit.Password: Any
